import { useWidget } from "../provider/context";

/**
 * Opener question pills rendered BELOW the Response (north-star layout:
 * InputBar → user bubble → answer → pills). Sourced from the `pdp-questions`
 * attribute (parsed once in custom-element.ts). Tapping a pill routes through
 * the same `sendMessage` path as typed input: product-context marker,
 * readiness gate, and welcome-suppression all apply uniformly.
 *
 * North-star behavior (Shiseido-Sandbox): the pill shelf drains as the
 * shopper engages. A pill the shopper has already clicked disappears so
 * they aren't looking at a question whose answer is already above them.
 * The remaining pills stay available until Shilpi's follow-up engine
 * replaces the set with dynamically-generated questions on each answer.
 * In this PR (gap period before follow-ups land), when the shopper has
 * exhausted all upfront pills, the shelf renders nothing — the InputBar
 * carries the shopper forward. By that point they've engaged with up to
 * four questions and typing feels natural; the InputBar placeholder
 * (`"Ask me anything about <productName>"`) stays visible above.
 *
 * No pill selection / highlighting: the north-star uses a right-aligned
 * user bubble above the answer as the "which question am I looking at?"
 * acknowledgement. Highlighting a pill in addition would be redundant.
 *
 * Follow-up questions (dynamically generated from the latest answer +
 * pageContext), the refresh / regenerate pill, and routing the clicked
 * pill into the main-chat window are all deliberate phase-2 items —
 * tracked as PR follow-ups. Static UPFRONT pills in this PR were
 * pre-generated by crawling the product catalog (Content Studio); they
 * are the merchant's curated opener menu, not per-session content.
 *
 * Lazy-connect contract: we do NOT warm the SCRT2 handshake on hover or
 * focus. The org/realm has a bounded concurrent SCRT2 session cap (~11k),
 * and the floating messaging widget already consumes one session per
 * engaged shopper independently of this widget. A passing cursor over a
 * pill is a bystander signal, not shopper intent, so warming on hover
 * would spin up sessions that sit unused. Instead, we rely on
 * `sendMessage`'s own `ensureConnected` guard: the first click does the
 * handshake inline (~1-2s cold), identical to the send button on a cold
 * InputBar. `disabled={!state.connectionReady}` keeps clicks gated until
 * the handshake lands.
 */
export function QuestionPills() {
  const { state, sendMessage } = useWidget();

  // Hide pills the shopper has already asked. Match is by exact string
  // equality — typed free-text questions won't match any pill, so typing
  // doesn't drain the shelf. Reset on SPA PDP navigation via
  // RESET_CONVERSATION (clears askedQuestions), so the new product's shelf
  // is full.
  const visible = state.pdpQuestions.filter((q) => !state.askedQuestions.includes(q));
  if (visible.length === 0) return null;

  // Disable all pills while a question is in-flight so the shopper can't
  // stack sends. Re-enables once the final SET_ANSWER (or SET_ERROR) lands.
  const busy = state.agentTyping || state.streamingText.length > 0;
  const disabled = !state.connectionReady || busy;

  return (
    <ul className="pills" aria-label="Suggested questions">
      {visible.map((q) => (
        <li key={q} className="pills-item">
          <button
            className="pill"
            type="button"
            disabled={disabled}
            onClick={() => {
              void sendMessage(q);
            }}
          >
            {q}
          </button>
        </li>
      ))}
    </ul>
  );
}
