import { useWidget } from "../provider/context";

/**
 * Opener question pills rendered above the input. Sourced from the
 * `pdp-questions` attribute (parsed once in custom-element.ts). Tapping a pill
 * routes through the same `sendMessage` path as typed input: product-context
 * marker, readiness gate, and welcome-suppression all apply uniformly.
 *
 * North-star behavior (Amazon Alexa for shopping / Shiseido-Sandbox):
 * the pre-generated question menu is a persistent surface — the shopper can
 * ask one question, read the answer, then ask another from the same list
 * without having to leave the PDP or retype anything. We therefore keep the
 * pills rendered after the first click; only their disabled state changes
 * while a question is in flight so the shopper can't stack three sends at
 * once. The clicked pill is marked `aria-pressed` and styled so the shopper
 * can see which question produced the answer below. The "selected" pill is
 * derived from `state.lastQuestion` directly — no local state — which means
 * on SPA PDP→PDP navigation (reducer RESET_CONVERSATION clears
 * lastQuestion) the selection naturally lifts for the new product's list,
 * and typing a free-text question (which won't match any pill text) leaves
 * all pills unselected.
 *
 * Follow-up questions (dynamically generated from the latest answer +
 * pageContext) and routing the clicked pill into the main-chat window are
 * both deliberate phase-2 items — see PRD. Static UPFRONT pills stay fixed
 * per product; they were pre-generated by crawling the product catalog and
 * are the merchant's curated opener menu, not per-session content.
 *
 * Lazy-connect contract: we do NOT warm the SCRT2 handshake on hover or
 * focus. The org/realm has a bounded concurrent SCRT2 session cap (~11k),
 * and the floating messaging widget already consumes one session per
 * engaged shopper independently of this widget. A passing cursor over a
 * pill is a bystander signal, not shopper intent, so warming on hover
 * would spin up sessions that sit unused. Instead, we rely on
 * `sendMessage`'s own `ensureConnected` guard: the first click does the
 * handshake inline (~1-2s cold), identical to the send button on a cold
 * InputBar. `disabled={!state.connectionReady}` keeps clicks gated until
 * the handshake lands.
 */
export function QuestionPills() {
  const { state, sendMessage } = useWidget();

  if (state.pdpQuestions.length === 0) return null;

  // Disable all pills while a question is in-flight so the shopper can't
  // stack sends. Re-enables once the final SET_ANSWER (or SET_ERROR) lands.
  const busy = state.agentTyping || state.streamingText.length > 0;
  const disabled = !state.connectionReady || busy;

  return (
    <ul className="pills" aria-label="Suggested questions">
      {state.pdpQuestions.map((q) => {
        const isSelected = state.lastQuestion === q;
        return (
          <li key={q} className="pills-item">
            <button
              className="pill"
              type="button"
              aria-pressed={isSelected}
              disabled={disabled}
              onClick={() => {
                void sendMessage(q);
              }}
            >
              {q}
            </button>
          </li>
        );
      })}
    </ul>
  );
}
